banmace:
  language: en
  mode: SPAWN
  toggle_key: RIGHT_CLICK_AIR
  teleport_effect:
    particle: PORTAL
    count: 100
    speed: 0.2
    offset: 0.5
  teleport_sound: ENTITY_ENDERMAN_TELEPORT
  banmace_modes:
    ban_duration: 600
    freeze_duration: 10
  item_customization:
    name_color: '&c'
    lore:
      - '&7This is the ultimate punishment tool.'
      - '&7Use it wisely.'
    additional_effects:
      mode_switch_sound: BLOCK_NOTE_BLOCK_PLING
      mode_switch_particle: SPELL_WITCH
