language: en
teleport_effect:
  particle: PORTAL
  count: 100
  speed: 0.2
  offset: 0.5
teleport_sound: ENTITY_ENDERMAN_TELEPORT

whitelist:
  enabled: true
  players: tester


message_display_mode: "chat"

check_for_updates: true
update_notify_in_game: true

item_customization:
  # https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
  name_color: '§c'
  bm-name: 'Ban Hammer 40k'
  item_material: "MACE"
  lore:
    - 'This is the ultimate punishment tool.'
    - 'Use it wisely.'

additional_effects:
  mode_switch_sound: BLOCK_NOTE_BLOCK_PLING
  mode_switch_particle: SPELL_WITCH

ban_mode:
  default_duration: "2h"

active_mode: SPAWN

logging:
  file_enabled: true
  discord:
    enabled: true
    webhook_url: ""