language: en
teleport_effect:
  particle: PORTAL
  count: 100
  speed: 0.2
  offset: 0.5
teleport_sound: ENTITY_ENDERMAN_TELEPORT
whitelist:
  enabled: true
  players:
message_display_mode: "chat" # Prob values: chat, actionbar, title
check_for_updates: true

item_customization:
  name_color: '§c'
  bm-name: 'Ban Hammer 40k'
  lore:
    - 'This is the ultimate punishment tool.'
    - 'Use it wisely.'

additional_effects:
  mode_switch_sound: BLOCK_NOTE_BLOCK_PLING
  mode_switch_particle: SPELL_WITCH