name: BanMace
version: '1.0.5'
main: org.nakolotnik.banMace.BanMace
api-version: '1.20'

commands:
  banmace:
    description: Give a BanMace to the player.
    usage: /<command> give
    aliases: [bh]
    permission: banmace.give
    permission-message: "You don't have permission to use this command."
  setlanguage:
    description: "Sets the plugin language."
    usage: "/setlanguage [en|ru]"
    permission: banmace.setlanguage
    permission-message: "You don't have permission to use this command."
  selectmode:
    description: "Opens the GUI to select the mode for BanMace."
    usage: "/selectmode"
    aliases: [sm]
    permission: banmace.selectmode
    permission-message: "You don't have permission to use this command."
permissions:
  banmace.use:
    description: Allows the player to use the BanMace.
    default: true
  banmace.give:
    description: Allows the player to receive the BanMace.
    default: op
  banmace.setlanguage:
    description: Allows the player to set the language.
    default: op
  banmace.selectmode:
    description: Allows the player to open the mode selection GUI.
    default: op

banmace:
  language: en
  mode: SPAWN
  toggle_key: RIGHT_CLICK_AIR
  teleport_effect:
    particle: PORTAL
    count: 100
    speed: 0.2
    offset: 0.5
  teleport_sound: ENTITY_ENDERMAN_TELEPORT
  banmace_modes:
    ban_duration: 600
    freeze_duration: 10
  item_customization:
    name_color: '&c'
    lore:
      - '&7This is the ultimate punishment tool.'
      - '&7Use it wisely.'
    additional_effects:
      mode_switch_sound: BLOCK_NOTE_BLOCK_PLING
      mode_switch_particle: SPELL_WITCH
