name: BanMace
version: '1.5'
main: org.nakolotnik.banMace.BanMace
api-version: '1.20'

commands:
  bm-setlanguage:
    description: Change the plugin language.
    usage: /bm-setlanguage [en|ru]
    permission: banmace.bm-setlanguage
  bm-give:
    description: Give the Ban Mace to a player.
    usage: /banmace bm-give
    permission: banmace.bm-give
  bm-changeview:
    description: Change the message display mode.
    usage: /bm-changeview <chat|actionbar|title>
    permission: banmace.bm-changeview
    permission-message: You do not have permission to use this command.

permissions:
  banmace.bm-setlanguage:
    description: Allows changing the plugin language.
    default: op

  banmace.give:
    description: Allows giving the Ban Mace to a player.
    default: op

  banmace.bm-changeview:
    description: Allows changing the message display mode (chat, actionbar, title).
    default: op