name: BanMace
version: '1.0'
main: org.nakolotnik.banMace.BanMace
api-version: '1.20'


commands:
  banmace:
    description: Give a BanMace to the player.
    usage: /<command> give
    aliases: [bh]

permissions:
  banmace.use:
    description: Allows the player to use the BanMace.
    default: true
  banmace.give:
    description: Allows the player to receive the BanMace.
    default: op

